exec-once = qs -c noctalia-shell
exec-once = discord
exec-once = steam
exec-once = systemctl --user start hyprpolkitagent
exec-once = /usr/lib/pam_kwallet_init
#xec-once = XDG_MENU_PREFIX=arch- kbuildsycoca6 --noincremental
exec-once = xrandr --output DP-1 --primary