windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# QT THEMING
env = QT_QPA_PLATFORMTHEME,kde
env = QT_QPA_PLATFORMTHEME=qt6ct
#env = QT_QPA_PLATFORMTHEME,qt6ct

#noctalia-ipc
$ipc = qs -c noctalia-shell ipc call
bind = SUPER, SPACE, exec, $ipc launcher toggle
bind = SUPER, S, exec, $ipc controlCenter toggle
bind = SUPER, comma, exec, $ipc settings toggle

env = EDITOR,kate
env = VISUAL,kate

env = WLR_NO_HARDWARE_CURSORS,1